name: d2d_dashboard

services:

  dashboard:
    container_name: D2D
    build:
      context: ./
    image: d2d
    restart: always
    hostname: d2d
    ports:
      - "5000:5000"
    volumes:
      - ./src:/D2D/src
    depends_on:
      - redis
      - postgres
    networks:
      - networks
  
  redis:
    container_name: D2D-Redis
    image: redis:7.2.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./db/redis:/data
    networks:
      - networks

  postgres:
    container_name: D2D-PostgreSQL
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ASUS
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
  
  pgadmin:
    container_name: D2D-pgAdmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  adminer:
    container_name: D2D-Adminer
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

networks:
  networks:
    driver: bridge
